/**
 * @description       : 
 * @author            : Venu Navuluri
 * @group             : 
 * @last modified on  : 18-09-2023
 * @last modified by  : Venu Navuluri
**/
public with sharing class PackageTriggerHandler extends TriggerHandler  {
   
        protected override void beforeInsert() {
        }
        protected override void afterInsert() {
         
        }
        protected override void afterDelete() {
         
        }
        protected override void afterUpdate() {
        
        }
}